apiVersion: v1
kind: Service              # 1
metadata:
  name: sa-frontend-lb
spec:
  type: NodePort       
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         
  selector:                
    app: sa-frontend       
